version: "3"
services:
  app:
    container_name: "data_science"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: data_science
    user: jovyan
    ports:
      - "10001:8888"
    volumes:
      - /work/scraping_data/:/home/jovyan/work/scraping_data/
      - /work/git/:/home/jovyan/work/git/
#    command: python3 /app/src/exec.py
