version: "3"
services:
  app:
    container_name: "python3.6"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: python_exec
    tty: true
    volumes:
      - $PWD/:/app
      - /work/:/work/
    working_dir: /app
    command: python3.6 ./src/exec.py
